export enum RosEventType {
  RETRY_MIC_COUNTDOWN = 'RETRY_MIC_COUNTDOWN',
  ANSWER_POPUP_CLOSED = 'ANSWER_POPUP_CLOSED',
  SAME_CHANGE_PAGE = 'SAME_CHANGE_PAGE',
  EMPTY_IMAGE_BUTTON_LIST = 'EMPTY_IMAGE_BUTTON_LIST'
}
